name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  cd:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.repository == 'iksaku/fimeats'
        uses: actions/checkout@v1
        with:
          lfs: true
      - name: Upload Assets to CDN
        if: github.repository == 'iksaku/fimeats'
        uses: iksaku/openstack-swift-action@stein
        env:
          OS_AUTH_URL: ${{ secrets.CDN_AUTH_URL }}
          OS_PASSWORD: ${{ secrets.CDN_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.CDN_REGION }}
          OS_TENANT_ID: ${{ secrets.CDN_TENANT_ID }}
          OS_USERNAME: ${{ secrets.CDN_USERNAME }}
        with:
          args: upload --object-name img fimeats public/img
      - name: Composer Install
        if: github.repository == 'iksaku/fimeats'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Build Node Assets
        run: |
          echo "Installing Yarn pakcages..."
          yarn install --silent --ignore-scripts --non-interactive --no-progress
          echo "Building Node Assets..."
          yarn prod
      - name: Deploy Code to Production
        if: github.repository == 'iksaku/fimeats'
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          SSH_PATH="$HOME/.ssh"
          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > "$SSH_PATH/deploy_key"
          echo "$SSH_PUBLIC_KEY" | tr -d '\r' > "$SSH_PATH/deploy_key.pub"
          chmod 700 "$SSH_PATH"
          chmod 600 "$SSH_PATH/known_hosts" "$SSH_PATH/deploy_key" "$SSH_PATH/deploy_key.pub"
          eval $(ssh-agent)
          ssh-add "$SSH_PATH/deploy_key"
          ssh-keyscan -H "$DEPLOY_HOST" >> "$SSH_PATH/known_hosts"
          php artisan deploy -s upload
