name: CI

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  php-ci:
    name: PHP Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Composer Install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Linter Test
        run: composer test:lint
  node-ci:
    name: NodeJS Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Yarn Install
        run: yarn install --silent --ignore-scripts --non-interactive --no-progress
      - name: Linter Test
        run: yarn lint
