name: CI/CD

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Composer Cache
        id: cache-composer
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.cache-composer.outputs.dir }}
          key: cache-composer-${{ hashFiles('composer.lock') }}
      - name: Install Composer Packages
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Lint Code
        run: composer test:lint

      - name: Setup Yarn Cache
        id: cache-yarn
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.cache-yarn.outputs.dir }}
          key: cache-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install Javascript Packages
        run: yarn install --silent --ignore-scripts --non-interactive --no-progress
      - name: Build Javascript Packages
        run: yarn production

#      - name: Test Application
#        run: php artisan test

      - name: Persist CSS Assets
        uses: actions/upload-artifact@v1
        with:
            name: assets-css
            path: public/css
      - name: Persist Javascript Assets
        uses: actions/upload-artifact@v1
        with:
          name: assets-js
          path: public/js
      - name: Persist Mix Manifest
        uses: actions/upload-artifact@v1
        with:
          name: mix-manifest
          path: public/mix-manifest.json
